"""create orders quarantine sync_log tables

Revision ID: 3da128cb8554
Revises: 
Create Date: 2026-08-11 10:25:42.185908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da128cb8554'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_shopify_order_id'), 'orders', ['shopify_order_id'], unique=True)
    op.create_table('quarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopify_order_id', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantine_shopify_order_id'), 'quarantine', ['shopify_order_id'], unique=False)
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('orders_fetched', sa.Integer(), nullable=True),
    sa.Column('orders_synced', sa.Integer(), nullable=True),
    sa.Column('orders_quarantined', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_log')
    op.drop_index(op.f('ix_quarantine_shopify_order_id'), table_name='quarantine')
    op.drop_table('quarantine')
    op.drop_index(op.f('ix_orders_shopify_order_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
